### ISSUE TITLE
how to determine different hash function for password

### ISSUE THREAD

**Issue by yougg** [youmark/pkcs8#6]
I create a private key by openssl pkcs8 like this:  
`openssl pkcs8 -in rsa.key -out pkcs8.key -topk8 -passout pass:xxxxx -v2 aes-256-cbc -iter 4096`  
when i call the function `ParsePKCS8PrivateKey`, got this error "pkcs8: incorrect password"

i'm sure my password is correct, so i think maybe something was wrong with password check.  
at this line:
https://github.com/youmark/pkcs8/blob/7e063b703ad990b1200b217e47201d1181cef53d/pkcs8.go#L204
it's hard code with `sha1.New` function.

then i go back to check my key file.  
`openssl asn1parse -in pkcs8.key`  
>0:d=0  hl=4 l=2478 cons: SEQUENCE          
4:d=1  hl=2 l=  88 cons: SEQUENCE          
6:d=2  hl=2 l=   9 prim: OBJECT            :PBES2  
17:d=2  hl=2 l=  75 cons: SEQUENCE          
19:d=3  hl=2 l=  42 cons: SEQUENCE          
21:d=4  hl=2 l=   9 prim: OBJECT            :PBKDF2  
32:d=4  hl=2 l=  29 cons: SEQUENCE          
34:d=5  hl=2 l=   8 prim: OCTET STRING      [HEX DUMP]:5624B6B1D069090A  
44:d=5  hl=2 l=   3 prim: INTEGER           :0F4240  
49:d=5  hl=2 l=  12 cons: SEQUENCE          
51:d=6  hl=2 l=   8 prim: OBJECT            :`hmacWithSHA256`  
61:d=6  hl=2 l=   0 prim: NULL              
63:d=3  hl=2 l=  29 cons: SEQUENCE          
65:d=4  hl=2 l=   9 prim: OBJECT            :aes-256-cbc  

As i checked the openssl manual page, it show this option:
> -v2prf alg
This option sets the PRF algorithm to use with PKCS#5 v2.0. A typical value value would be `hmacWithSHA256`. If this option isn't set then the default for the cipher is used or `hmacWithSHA256` if there is no default.
　  
Some implementations may not support custom PRF algorithms and may require the `hmacWithSHA1` option to work.

So i tried again with sha1 hash function to convert the key:  
`openssl pkcs8 -in rsa.key -out pkcs8.key -topk8 -passout pass:xxxxx -v2 aes-256-cbc -iter 4096 -v2prf hmacWithSHA1`

`ParsePKCS8PrivateKey` worked fine this time.  
　  
Is there any way to auto determine the hash function with sha1 and sha256 ?

**Comment by youmark** [comment]
Parsing private key with hmacWithSHA256 is now added. The code is able to parse based on PRF oid in the asn1 blob.
